#!/bin/bash

# Define variables
INSTANCE_ID=<contabo_vps_id>
SNAPSHOT_NAME=$(date +'%B-%d')-ok
TELEGRAM_BOT_TOKEN=<telegram_bot_token>
TELEGRAM_CHAT_ID=<telegram_chat_id>

# Function to send message to Telegram
send_telegram_message() {
  local message=$1
  curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d chat_id=$TELEGRAM_CHAT_ID -d text="$message"
}

# Get the list of snapshots and count them
SNAPSHOTS=$(cntb get snapshots $INSTANCE_ID)
SNAPSHOT_COUNT=$(echo "$SNAPSHOTS" | grep -c snap)

# If there are 2 snapshots or more, delete the oldest one
if [ "$SNAPSHOT_COUNT" -ge 2 ]; then
  OLDEST_SNAPSHOT=$(echo "$SNAPSHOTS" | awk 'NR==2 {print $1}')
  echo "Deleting oldest snapshot: $OLDEST_SNAPSHOT"
  cntb delete snapshot $INSTANCE_ID $OLDEST_SNAPSHOT
  if [ $? -eq 0 ]; then
    send_telegram_message "Oldest snapshot $OLDEST_SNAPSHOT deleted successfully."
  else
    send_telegram_message "Failed to delete oldest snapshot $OLDEST_SNAPSHOT."
  fi
fi

# Create the new snapshot
cntb create snapshot $INSTANCE_ID --name "$SNAPSHOT_NAME"
if [ $? -eq 0 ]; then
  # Verify the snapshot creation
  if cntb get snapshots $INSTANCE_ID | grep -q $SNAPSHOT_NAME; then
    send_telegram_message "Snapshot '$SNAPSHOT_NAME' created successfully."
  else
    send_telegram_message "Snapshot '$SNAPSHOT_NAME' creation failed."
  fi
else
  send_telegram_message "Failed to create snapshot '$SNAPSHOT_NAME'."
fi
